package cm.ramassage.Controller;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.*;

/**
 * Created by Angel on 26.08.17.
 */

@WebServlet("/register")
public class Register extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        PrintWriter out = resp.getWriter();

        String name = req.getParameter("nachname");
        String vorname = req.getParameter("vorname");
        String wohnort = req.getParameter("ort");
        String telenr = req.getParameter("telefon");
        String geburtsdatum = req.getParameter("geburtsdatum");
        String geburtsort = req.getParameter("geburtsort");
        String nationalite = req.getParameter("ql_land");
        String email = req.getParameter("email");
        String pass = req.getParameter("pass");

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_reise?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","nasperesse","mysql");

            PreparedStatement ps=con.prepareStatement(
                    "insert into User (aufenthaltsort, email, geburtsdatum, geburtsort, mdpasse, name, nationaliaet, telefonnr, vorname) values(?,?,?,?,?,?,?,?,?)", Statement.RETURN_GENERATED_KEYS);


            ps.setString(1,wohnort);
            ps.setString(2,email);
            ps.setString(3,geburtsdatum);
            ps.setString(4,geburtsort);
            ps.setString(5,pass);
            ps.setString(6,name);
            ps.setString(7,nationalite);
            ps.setString(8,telenr);
            ps.setString(9,vorname);


            int i=ps.executeUpdate();

            ResultSet tableKeys = ps.getGeneratedKeys();

            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);

            System.out.println(autoGeneratedID);
            ps.setInt(1,autoGeneratedID);
            if(i>0){


                resp.sendRedirect("home.jsp");
            }
            else  out.print("You are successfully registered...");



        }catch (Exception e2) {System.out.println(e2);}

        out.close();
    }


}
