package cm.ramassage.Configuration;

import cm.ramassage.Controller.Registrierung;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import java.sql.*;

public class Test {


    public static void main(String[] args) {


        AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext(AppConfig.class);

        ctx.scan("cm.ramassage");

        Registrierung registrierung =(Registrierung ) ctx.getBean("control");


        registrierung.neuUser("Modjo","ange","Yaounde","285828282","12.06.1992","Yokadouma","Kamerun","ange@yahoo.fr","moi");

        registrierung.neuUser("Djoko","jaures","Douala","28528282","12.06.1980","Dakar","Senegal","jaures@yahoo.fr","nadine");

        registrierung.neuUser("Matebs","Ida","Buea","28582828332","12.06.1984","Paris","Francais","Ida@yahoo.fr","shekina");

        registrierung.neuUser("Djouguela","Yves","Bamenda","28582833282","12.06.1982","Geselkirchen","Deutsch","Carlos@yahoo.fr","bigd");

        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_reise?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC","nasperesse","mysql");

            PreparedStatement ps=con.prepareStatement(
                    "insert into User (aufenthaltsort, email, geburtsdatum, geburtsort, mdpasse, name, nationaliaet, telefonnr, vorname) values(?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS);



            ps.setString(1,"yde");
            ps.setString(2,"fi@ag.ge");
            ps.setString(3,"12.4.4");
            ps.setString(4,"geburtsort");
            ps.setString(5,"nas");
            ps.setString(6,"vieux");
            ps.setString(7,"malienne");
            ps.setString(8,"353q42q2343q");
            ps.setString(9,"jeune");


            int i=ps.executeUpdate();

            ResultSet tableKeys = ps.getGeneratedKeys();

            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);

            System.out.println(autoGeneratedID);
            ps.setInt(1,autoGeneratedID);
            if(i>0){


                System.out.print("effectuer");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        registrierung.istAuthentified("fi@ag.ge","nas");

        registrierung.istAuthentified("ange@yahoo.fr","moi");

        registrierung.istAuthentified("jaures@yahoo.fr","nadine");

        registrierung.istAuthentified("Ida@yahoo.fr","shekina");

        registrierung.istAuthentified("Carlos@yahoo.fr","bigd");

    }
}
